appname = ${APPNAME}
httpport = ${HTTPPORT}
runmode = ${RUNMODE}
autorender = ${AUTORENDER}
copyrequestbody = ${COPYREQUESTBODY}
EnableDocs = ${ENABLEDOCS}
EnableXSRF = ${ENABLEXSRF}
xray = ${XRAY}
terceroService = "${TERCEROSERVICE}"
sabaticosService = "${SABATICOSSERVICE}"