appname = sabaticos_mid
httpport = ${SABATICOS_MID_HTTPPORT}
runmode = ${SABATICOS_MID_RUNMODE||prod}
copyrequestbody = true

terceroService = ${SABATICOS_MID_TERCEROS}
sabaticosService = ${SABATICOS_MID_SABATICOS_CRUD}
gestorDocumentalService = ${SABATICOS_MID_GESTORDOCUMENTAL}
documentosService = ${SABATICOS_MID_DOCUMENTOS_CRUD}
academicaJbpmService = ${SABATICOS_MID_ACADEMICAJBPM}