appname = sabaticos_mid
httpport = ${SABATICOS_MID_HTTPPORT}
runmode = ${SABATICOS_MID_RUNMODE}
EnableDocs = ${SABATICOS_MID_ENABLEDOCS}
copyrequestbody = ${SABATICOS_MID_COPYREQUESTBODY}
xray = ${SABATICOS_MID_XRAY}

terceroService = ${SABATICOS_MID_TERCEROS}
sabaticosService = ${SABATICOS_MID_SABATICOS_CRUD}
gestorDocumentalService = ${SABATICOS_MID_GESTORDOCUMENTAL}
documentosService = ${SABATICOS_MID_DOCUMENTOS_CRUD}